# Generated by Django 5.2.1 on 2025-06-01 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('yoozak_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifiant Yoozak')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région')),
                ('product', models.CharField(max_length=200, verbose_name='Article')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('creation_date', models.DateTimeField(verbose_name='Date de création')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('status', models.CharField(choices=[('affecte', 'Affecté'), ('non_affectee', 'Non affectée'), ('erronnee', 'Erronée'), ('doublon', 'Doublon')], default='non_affectee', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('non_paye', 'Non payé'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé')], default='non_paye', max_length=20, verbose_name='État paiement')),
                ('delivery_status', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('retournee', 'Retournée')], default='en_preparation', max_length=20, verbose_name='État livraison')),
                ('motifs', models.TextField(blank=True, null=True, verbose_name='Motifs')),
                ('modifications', models.TextField(blank=True, null=True, verbose_name='Modifications')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name="Raison de l'annulation")),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Source')),
                ('source_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Source')),
                ('client_type', models.CharField(choices=[('nouveau', 'Nouveau Client'), ('fidele', 'Client Fidèle')], default='nouveau', max_length=20, verbose_name='Type de client')),
                ('remaining_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reste à payer')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date paiement')),
                ('returned_piece', models.BooleanField(default=False, verbose_name='Pièce retournée')),
                ('delivery_notes', models.TextField(blank=True, null=True, verbose_name='Observation livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Agent confirmation')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.operator', verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, verbose_name='Code produit')),
                ('size', models.CharField(max_length=20, verbose_name='Pointure')),
                ('color_ar', models.CharField(max_length=50, verbose_name='Couleur (arabe)')),
                ('color_fr', models.CharField(max_length=50, verbose_name='Couleur (français)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'ordering': ['created_at'],
            },
        ),
    ]
