# Generated by Django 5.2.1 on 2025-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('non_affectee', 'Non affectée'), ('affectee', 'Affectée'), ('en_cours_confirmation', 'En cours de confirmation'), ('confirmee', 'Confirmée'), ('erronnee', 'Erronée'), ('doublon', 'Doublon')], default='non_affectee', max_length=25, verbose_name='Statut'),
        ),
    ]
