# Generated by Django 5.2.1 on 2025-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('erronnee', 'Erronée'), ('injoignable', 'Injoignable'), ('pas_interesse', 'Pas intéressé')], max_length=20, null=True, verbose_name="Raison de l'annulation"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('non_affectee', 'Non affectée'), ('affectee', 'Affectée'), ('en_cours_confirmation', 'En cours de confirmation'), ('confirmee', 'Confirmée'), ('erronnee', 'Erronée'), ('doublon', 'Doublon'), ('annulee', 'Annulée')], default='non_affectee', max_length=25, verbose_name='Statut'),
        ),
    ]
