# Generated by Django 5.2.1 on 2025-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=50, unique=True, verbose_name='Code Article')),
                ('article_name', models.CharField(max_length=255, verbose_name='Nom Article')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pointure')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stock_photos/', verbose_name='Photo')),
                ('quantity_available', models.IntegerField(default=0, verbose_name='Quantité Disponible')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière Mise à Jour')),
            ],
        ),
    ]
