# Generated by Django 5.2.1 on 2025-06-01 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_url', models.URLField(verbose_name='URL de la feuille Google Sheet')),
                ('sheet_name', models.CharField(max_length=100, verbose_name='Nom de la feuille')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Google Sheet',
                'verbose_name_plural': 'Configurations Google Sheet',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de synchronisation')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('partial', 'Partiel')], max_length=10, verbose_name='Statut')),
                ('records_imported', models.IntegerField(default=0, verbose_name='Enregistrements importés')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Erreurs')),
                ('triggered_by', models.CharField(max_length=100, verbose_name='Déclenché par')),
                ('sheet_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sync.googlesheetconfig')),
            ],
            options={
                'verbose_name': 'Log de synchronisation',
                'verbose_name_plural': 'Logs de synchronisation',
                'ordering': ['-sync_date'],
            },
        ),
    ]
