# Generated by Django 5.2.1 on 2025-06-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('printed_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('label_path', models.CharField(blank=True, max_length=255, null=True, verbose_name="Chemin de l'étiquette")),
            ],
            options={
                'verbose_name': 'Étiquette logistique',
                'verbose_name_plural': 'Étiquettes logistiques',
            },
        ),
    ]
